### ISSUE TITLE
Page builder responsiveness broken

### ISSUE THREAD

**Issue by Code-Divine** [ThemeFuse/Unyson#1628]
Since the last update of the page builder extension the responsiveness broke. The reason for that is because the the fw-container class in framework-grid.css uses fixed width in the media queries instead of max-width.

Currently is something like this:

```css
.fw-container {
    width: 1170px;
}
@media (min-width: 992px)
.fw-container {
    width: 970px;
}
@media (min-width: 768px)
.fw-container {
    width: 750px;
}
```

I don't remember that css even existing before the update but if it's needed using max-width instead of width fixes the problem.
