### ISSUE TITLE
Image picker , brake after setting

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2050]
Can we have image-picker   brake after setting to drop images on second line
Currently the width is at auto 
https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/image-picker/class-fw-option-type-image-picker.php#L202

and it just keeps on adding images in one row making it look out of line with the rest of the options

![screenshot_15](https://cloud.githubusercontent.com/assets/2340172/18790699/0c728f78-81b0-11e6-85a1-c28942a63779.jpg)

I know I can CSS it but it would be just easier to do 

```
    'type' => 'image-picker',
    'brakeafter' => 3,
```

or something similar that would brake after every 3rd ( option dependent ) image

**Comment by albertso** [comment]
Target the option with a class:

```php
        'type' => 'image-picker',
        'attr' => array( 'class' => 'narrow' ),
```
Enqueue css in admin, to limit the sizes so that new rows will be formed:
```css
    .fw-backend-option-type-image-picker.narrow .thumbnails {
        max-width: 350px;
    }
    .fw-backend-option-type-image-picker.narrow .thumbnail img {
        max-width: 100px;
    }
```

Set the size of image if css isn't enough:

```php
        'choices' => array(
            'value-1' => array(
                'small' => array(
                    'src' => get_template_directory_uri() .'/images/thumbnail.png',
                    'height' => 100 // pixels
                    'width' => 100 // pixels
                ),
            )
        ),
```

**Comment by GheorgheP** [comment]
I think this is a very specific need, that can be very easy implemented with some custom CSS:

```php
'picker' => array(
	'type'    => 'image-picker',
	'value'   => array(),
	'label'   => __( 'Pick', 'fw' ),
	'attr'    => array(
		'class' => 'break-3'
	),
	'choices' => array(
		'1' => 'ICON URL',
		'2' => 'ICON URL',
		'3' => 'ICON URL',
		'4' => 'ICON URL',
		'5' => 'ICON URL',
	)
),
```

and the CSS part:

```css
.fw-option-type-image-picker.break-3 ul.thumbnails>li:nth-child(4) {
    clear: left;
}
```
