### ISSUE TITLE
[suggestion] Manage sidebar style suggestion

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#214]
Not sure if you are up for it but for me something like this kinda fits better
http://screencast.com/t/b99vFBQ0
than this
http://screencast.com/t/Bth0vSvn

```css
.fw-ext-sidebars-wrap {
	width:98%;
	clear: both;
         // add code below
	display:block;
    -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
	background: #fff;
	padding:20px;
	border: 1px solid #e5e5e5;
	margin-left:-5px;
	-webkit-box-shadow: 0 1px 1px rgba(0,0,0,.04);
	box-shadow: 0 1px 1px rgba(0,0,0,.04);
}
.fw-ext-sidebars-wrap .fw-sidebars-tabs-list ul li.ui-state-active a.nav-tab {
	color: #000;
	background: 0 0;
	border-bottom-color: #fff; // this is changed
}
```

What do you think?
