### ISSUE TITLE
[Question] Title template for addable box

### ISSUE THREAD

**Issue by Valtasaar** [ThemeFuse/Unyson#2157]
Hi!
How can I customize my template like that:
![default](https://cloud.githubusercontent.com/assets/13382888/19853227/1388d40c-9f79-11e6-85ed-7aec6bfff41d.JPG)

**Comment by moldcraft** [comment]
Do you mean to have incremental index (1, 2, 3, ...) on each box that will be updated on box position change? If yes, it's not possible without custom javascript.

**Comment by Valtasaar** [comment]
Yes, it I mean. Where I can write my js code for this?

**Comment by moldcraft** [comment]
The indexes "1, 2, 3, ..." are stored in box options or are just for visual purposes? Why you need them?

**Comment by Valtasaar** [comment]
Yes, only for visual purposes in the title.
```html
<h2 class="hndle ui-sortable-handle">
...
    <span>Hello 1</span>
...
</h2>

<h2 class="hndle ui-sortable-handle">
...
    <span>Hello 2</span>
...
</h2>
```
and so on.

If there is a possibility use the indexes for this purposes, then tell me how to do it. Or what other ways.

**Comment by moldcraft** [comment]
You can achieve that from css

```css
#YOUR_OPTION_ID.fw-option-type-addable-box .fw-option-boxes > .fw-option-box:nth-child(1) .fw-postbox > h2 > span:after {
    content: ' 1';
}
#YOUR_OPTION_ID.fw-option-type-addable-box .fw-option-boxes > .fw-option-box:nth-child(2) .fw-postbox > h2 > span:after {
    content: ' 2';
}
...
```

You can also [limit the boxes](http://manual.unyson.io/en/latest/options/built-in/addable-box.html#content) that can be added if you don't want to add 1k lines of css for 100+ boxes.
