### ISSUE TITLE
PNG image preview

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson#217]
We have this case in the theme we are working on: 

We have this png image as a bg in a column - http://joxi.ru/12Mx7ygClK8WmJ and because it's white and also has some opacity set, in the image upload preview I see this: http://joxi.ru/82Q4pJjTwd8Pmd

We'll need to find a solution to display a gray bg there or something for png images. Look how WordPress handles this: http://joxi.ru/v29ydbRiZYjy2G

**Comment by moldcraft** [comment]
@DimiBaitanciuc maybe something like this?

![ss](http://static.md/d66d6a9024e4d4828f8d84fedcc4bc4e.png)

```css
.fw-option-type-upload.images-only .thumb img,
.fw-option-type-multi-upload.images-only .thumb img {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAL0lEQVQ4T2Pcv3//fwY8wMHBAZ80A+OoAcMiDP4DAb6IPnDgAP50MGoAA+PQDwMAkx5R0SMOKDEAAAAASUVORK5CYIIA');
}
```
