### ISSUE TITLE
Youtube Embed module collapsing when clicked

### ISSUE THREAD

**Issue by graphicdesignbyemily** [ThemeFuse/Unyson#2515]
I have added height and width - tried different values, tried leaving height black, still collapses when you click play.

[link here](https://www.bayviewresorthamptons.com/the-resort/)

**Comment by GheorgheP** [comment]
This is because of this code in https://www.bayviewresorthamptons.com/wp-content/themes/accommodation/assets/css/accommodation-fw-utility.css?ver=2.1.1 line `63`:

```css
img,
iframe,
embeded {
    max-width: 100%;
    height: auto;
}
```

The css rule `height: auto` overwrites the iframe `height` attribute value, but iframes do not behavior like images.

You could try trick like this:

```css
.fw-video.video-ifrm .embed-youtube {
    height: 0;
    width: 100%;
    padding-top: 56%;
    position: relative;
}

.fw-video.video-ifrm .embed-youtube>iframe {
    position: absolute;
    top: 0;
    left: 0;
    max-width: 100%;
    height: 100%;
}
```

This will make the `.embed-youtube` container height dependent from it's width, same like the `<img>` tag when have the `height: auto` rule. Then the `<iframe>` will just fit in the container width and height. In result you'll get a video `<iframe>` that will respect it's aspect ration like the video should do.

Why I'm not very happy of this solution? Because there the `<iframe>` tag has `position: absolute` using `position: absolute` very often is not recommend as it consumes some browser resources, but in your case it shouldn't affect the browser performance at all unless you don not intend to make a video gallery page with 300 videos on it.

PS: One more thing, if you'll implement this solution, then set the `width` and `height` shortcode attribute values for the `.embed-youtube` container, not for `<iframe>`, otherwise they will not have any effect as the iframe size is controlled by CSS now `width: 100%; height: 100%;`.
