### ISSUE TITLE
Unyson accordion look and bug.

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson#281]
Hi,

I'm looking into a way to change the look of the accordion (Unyson shortcode) and I don't know how to do that.
There is my current accordion : http://terra.nicolas-duclos.com/services/

What I would like is : 
- Be able to use "font awesome" icon as the icon to open/close the section. Like one icon to open and another one to close. Now I know that they are made with CSS, but with "font-awesome" it's in the HTML before the title or after.
- Also, I would like the icon on the right of the title. That can be made with HTML like I said, but everything with Wordpress is with PHP and I can't find where to edit that, because I'm not really good in PHP.

Secondly, the bug. Is it possible to fixe the "page jump" bug when you are opening/closing a section. Just look at my website and look the footer. It's just weird and annoying. Can you fixe this to have something like that : http://css3.bradshawenterprises.com/accordions/ This exemple is showing how a fixe height is not doing a "page jump" bug.
Or here http://tympanus.net/Tutorials/CSS3Accordion/index.html , there is another exemple where you are able to open and close all section at the same time.

Thank you to help me :)

**Comment by dobromir-hristov** [comment]
Jump is the result of the page shortening and expanding from the accordion. Unless you put a min height or similar on the whole accordion, I dont see it happening. 
The icons can be added with :before and :after pseudo elements... pretty easy in fact.
```css
.title:after{
   font-family: Font Awesome;
   content: "\" ;  
// check this from their webpage 
   display: block;
// Other things you need 

}
```

**Comment by moldcraft** [comment]
> Jump is the result of the page shortening and expanding from the accordion.

I think there is realy a jumping because of a margin inside accordion,  and on slide open/close it is not animated but it disappear/appear and makes the page "jump". There should be used padding instead of margin, padding is animated.

**Comment by Nic787** [comment]
Can it be fixed via an update or I will have to do it manually everytimes I have an update?
Is it possible to have "auto" height where it make something like the second exemple?

Thank you for the tips to add my own icon.

**Comment by Nic787** [comment]
Do you think it could work if I put that for the accordion?

<script>
  $(function() {
    $( "#accordion" ).accordion({
      heightStyle: "content"
    });
  });
  </script>


And 

.title:after{
   font-family: Font Awesome;
   content: "\" ;  

doesn't work. I saw that the original icon is in CSS, but it's changing with a script each time you click on the title. I'm not really good in Jquery.

I would like something like that http://image.noelshack.com/fichiers/2015/07/1423841988-capture-d-ecran-2015-02-13-a-10-38-52.png , but I need all icon at the same place and not right on the right of each word, because it will look weird.

Thank you

**Comment by danyj** [comment]
See this one also while you looking at accordion
word-wrap bug

http://prntscr.com/6agc4h
http://prntscr.com/6agcb9
http://prntscr.com/6agcfp
http://prntscr.com/6ageok

**Comment by GheorgheP** [comment]
Unyson Accordion shortcode is just the minimum of what and accordion shortcode will require:
- Accordion Title
- Accordion Content

So in case there are some needs wish custom icons, images etc., this is just another design, may be another accordion library, so feel free to create your own accordion shortcode. You don't even need to refer to the Unyson version of that shortcode.

And specifically for you case, just modify the accordion view, and add in the title a icon with FontAwsome in the place you need it: before title or after, and then play with css to place it correctly it:
```php
<h3 class="fw-accordion-title"><i class="fa expand"></i><?php echo $tab['tab_title']; ?></h3>
```

Then add this in css:
```css
.fw-accordion .fw-accordion-title .ui-icon {
	display: none;
}

.fw-accordion-title i {
	position: absolute;
	right: 15px;
	opacity: 0.8;
}

.fw-accordion .fw-accordion-title i:before{
	content: "\f055";
}

.fw-accordion .fw-accordion-title.ui-state-active i:before{
	content: "\f056";
}
```

And you should get something like this: http://screencast.com/t/w4bhTQNqttKp

What about the second problem, it will be solved in the next version of the Shortcodes extension
