### ISSUE TITLE
Content within Pagebuilders Popups limited to 428px?

### ISSUE THREAD

**Issue by ecksite** [ThemeFuse/Unyson#3198]
Hi there,

is there a reason, why the "inner content" within the page builders popups are limited to 428px? See screenshot attached (Safari 10.1.2, MacOS 10.12)
If not, please remove the max-width or increase it dramatically. 

see, backend-options.css:
`
.fw-backend-option-design-customizer > .fw-backend-option-input.width-type-fixed > .fw-inner,
.fw-backend-option-fixed-width {
	width: 100%;
	max-width: 428px;
}
`

![modal_max-width](https://user-images.githubusercontent.com/28386816/36301302-9a971440-1304-11e8-9547-fa5ce5d6c097.jpg)

Thank you.

**Comment by ViorelEremia** [comment]
Where did you get that? I tested with scratch theme in customizer with large popup ```'size' => 'large'``` and is fine.

**Comment by ecksite** [comment]
I get that in elements within the page builder (didn't test it in customizer popups), for example when overriding the popup size of the text block shortcode element. It doesn't matter if i override it, with a custom shortcode (framework-customizations), or change the build in text-block shortcode element within the unyson plugin directory (for testing purposes).

Please look into the CSS class. Its located here:
[Line 932 in framework/static/css/backend-options.css](https://github.com/ThemeFuse/Unyson/blob/be11ea3e8a351f340ec18d0600eb4a7dc0e87f79/framework/static/css/backend-options.css#L932)

```css
.fw-backend-option-design-customizer > .fw-backend-option-input.width-type-fixed > .fw-inner,
.fw-backend-option-fixed-width {
	width: 100%;
	max-width: 428px;/*THIS ONE SEEMS TO CAUSE THE ISSUE*/
}
```

I am overriding the popup size by adding the following element to the array of the shortcodes config file:
```php
    'popup_size'  => 'large',
```

P.s. I also tested it in another blank demo installation on localhost, using safari AND firefox on macos
